[build]
  # Direktorij gdje su vaši frontend fileovi (HTML, CSS, JS)
  publish = "."
  
  # Direktorij gdje su vaše Netlify Functions
  functions = "netlify/functions"

[functions]
  # Node.js verzija za funkcije
  node_bundler = "esbuild"
  
  # Eksterni moduli koji su potrebni
  external_node_modules = ["node-fetch"]

# Redirects za funkcije
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# CORS headers za sve funkcije
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"