# netlify.toml
# Konfiguracija za Netlify deployment

[build]
  # Specify the directory where the build outputs files
  publish = "."
  
  # Command to run for the build (ako imaš build proces)
  # command = "npm run build"

[functions]
  # Direktorij gdje se nalaze Netlify funkcije
  directory = "netlify/functions"
  
  # Node.js bundler za optimizaciju
  node_bundler = "esbuild"

# Environment varijable za produkciju (već postavljena na dashboard-u)
# [context.production.environment]
#   api = "your_openrouter_api_key_here"

# Redirects (ako trebas)
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# Headers za sigurnost
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Specifični headers za funkcije
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"